-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 23:38:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffers` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `coffers` ;

-- -----------------------------------------------------
-- Table `coffers`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffers`.`menu` (
  `ItemCode` INT(11) NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(50) NULL DEFAULT NULL,
  `Description` TINYTEXT NULL DEFAULT NULL,
  `Price` DECIMAL(13,4) NULL DEFAULT NULL,
  PRIMARY KEY (`ItemCode`),
  INDEX `ItemName` (`ItemName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffers`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffers`.`users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `FName` VARCHAR(35) NULL DEFAULT NULL,
  `LName` VARCHAR(35) NULL DEFAULT NULL,
  `Dob` DATE NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `Password` VARCHAR(50) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(50) NULL DEFAULT NULL,
  `Bio` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `Email` (`Email` ASC),
  INDEX `FName` (`FName` ASC),
  INDEX `LName` (`LName` ASC),
  INDEX `PhoneNumber` (`PhoneNumber` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffers`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffers`.`orders` (
  `OrderID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderDetails` VARCHAR(150) NULL DEFAULT NULL,
  `PersonID` INT(11) NULL DEFAULT NULL,
  `OrderStatus` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `PersonID` (`PersonID` ASC),
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`PersonID`)
    REFERENCES `coffers`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffers`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffers`.`orderdetails` (
  `orderNumber` INT(11) NOT NULL,
  `productCode` INT(11) NOT NULL,
  `quantityOrdered` INT(11) NULL DEFAULT NULL,
  `priceEach` DECIMAL(13,4) NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`, `productCode`),
  INDEX `productCode` (`productCode` ASC),
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `coffers`.`orders` (`OrderID`)
    ON UPDATE CASCADE,
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`productCode`)
    REFERENCES `coffers`.`menu` (`ItemCode`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
